-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.

BEGIN;


CREATE TABLE IF NOT EXISTS public."Question"
(
    id integer NOT NULL,
    post_type integer NOT NULL,
    body text,
    score integer,
    accepted_answer integer,
    created_date text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."PostType"
(
    "Id" integer NOT NULL,
    "Description" text NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Answer"
(
    id integer NOT NULL,
    question_id integer NOT NULL,
    post_type integer NOT NULL,
    body text,
    score integer,
    created_date text,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Question"
    ADD FOREIGN KEY (post_type)
    REFERENCES public."PostType" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Quesion"
    ADD FOREIGN KEY (accepted_answer)
    REFERENCES public."Answer" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Answer"
    ADD FOREIGN KEY (question_id)
    REFERENCES public."Question" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Answer"
    ADD FOREIGN KEY (post_type)
    REFERENCES public."PostType" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
