-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.

BEGIN;


CREATE TABLE IF NOT EXISTS public.question
(
    id integer NOT NULL,
    post_type integer NOT NULL,
    body text,
    score integer,
    accepted_answer integer,
    created_date text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.post_type
(
    id integer NOT NULL,
    description text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.answer
(
    id integer NOT NULL,
    question_id integer NOT NULL,
    post_type integer NOT NULL,
    body text,
    score integer,
    created_date text,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.question
    ADD FOREIGN KEY (post_type)
    REFERENCES public.post_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.quesion
    ADD FOREIGN KEY (accepted_answer)
    REFERENCES public.answer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
END;

